[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_SUPABASE_URL = "https://xcgqfcqjxtfhuqpazfrv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZ3FmY3FqeHRmaHVxcGF6ZnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDUwNTMsImV4cCI6MjA1OTAyMTA1M30.8PP5E2Ik6MZ0RJsnxLjBXo1tg2go6oOIS85StVGlNiM"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[edge_functions]]
function = "hello"
path = "/test"