[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_SUPABASE_URL = "https://xcgqfcqjxtfhuqpazfrv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZ3FmY3FqeHRmaHVxcGF6ZnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDUwNTMsImV4cCI6MjA1OTAyMTA1M30.8PP5E2Ik6MZ0RJsnxLjBXo1tg2go6oOIS85StVGlNiM"
  VITE_SUPABASE_SERVICE_ROLE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1bnliamJmaXV3bWtndXN6cmdvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTMzOTI2MywiZXhwIjoyMDYwOTE1MjYzfQ.x12Oy5bbWuZd9HkKT5_d_bzTCQEa9mEohl1VxwEzacU"
  VITE_SUPABASE_JWT_SECRET = "za/NZAaZ73ckQMDxcFjNY/tmaeim+3/6sxOnjEFFzqmNl7JXYquSJIX4z6T8Q1wTV5ncPg6aqir/0vlGde1rkg=="

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[edge_functions]]
function = "hello"
path = "/test"