[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[edge_functions]]
function = "hello"
path = "/test"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"